The support of the National Centre of Competence in Research (NCCR) Digital Fabrication funded by the Swiss National Science Foundation (SNSF) is acknowledged (Agreement ID #51NF40141853).

The support of École Polytechnique Fédérale de Lausanne (EPFL) also is acknowledged with many thanks.
